[workspace]


[[package]]
name = "juniper_relay_helpers"
version_group="juniper_relay_helpers"
publish = true

[[package]]
name = "juniper_relay_helpers_codegen"
version_group="juniper_relay_helpers"
publish = true

[[package]]
publish = false
